# Sample settings (all accepted values)
all-settings:
  branch-protection:
    dissmiss-stale-reviews: false
    required-review-count: 1
  features:
    issues: true
    projects: true
    wiki: true
    downloads: false
  allow:
    squash-merge: true
    merge-commit: true
    rebase-merge: true
  delete-branch-on-merge: true
  labels:
    bug:
    feature:
    good first issue:

# My custom settings
my-settings: &my-settings
  features:
    issues: true
  allow:
    squash-merge: true
    merge-commit: true
    rebase-merge: true
  delete-branch-on-merge: false

# List of repos to update. This is the only key actually accessed by reposettings
repos:
  roobre/tcache: *my-settings
  roobre/ffxivapi: *my-settings
