on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: actions/checkout@v2
      - run: pip3 install -r requirements.txt
      - name: Run tests
        run: coverage run -m unittest discover
      - name: Report code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: d075a7a68749e26b1932888304319b62fcd65d6318895c4cebdf75e3765447fa
        with:
          coverageCommand: coverage xml

  release:
    needs: [ test ]
    name: Build and push dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build . -t roobre/reposettings
      - uses: docker/login-action@v1
        with:
          username: roobre
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push roobre/reposettings

  self-test:
    needs: [ release ]
    name: Example and self-test job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.ACTUAL_TOKEN }}
          config: |
            # My custom settings
            my-settings: &my-settings
              features:
                issues: true
              allow:
                squash-merge: true
                merge-commit: true
                rebase-merge: true
              delete-branch-on-merge: true

            # List of repos to update. This is the only key actually accessed by reposettings
            repos:
              roobre/reposettings: *my-settings
